// storeonwheels.client/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import axios from 'axios';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
  public message = "";

  constructor(private http: HttpClient) {}

  async ngOnInit() {
    const response: Record<string, string> = (await axios.get("api/v1/heartbeat")).data;
    this.message = response["message"];
  }

  title = 'storeonwheels.client';
}

<h1 id="tableLabel">Weather forecast</h1>

<p>Message: {{message}}</p>

// storeonwheels.client/src/App.tsx
import './App.css';
import { useEffect, useState } from "react";
import axios from "axios";

function App() {
  const [message, setMessage] = useState<string>();

  useEffect(() => {
    (async () => {
      try {
        const response: Record<string, string> = (await axios.get("api/v1/heartbeat")).data;
        console.log(response);        
        setMessage(response["message"]);
      } catch (error) {
        console.log(error);
      }
    })();
  }, []);

  return <>
    <p>{message}</p>
  </>
}

export default App;
